### ISSUE TITLE
Create a Basic Start Menu

### ISSUE THREAD

**Issue by Ofthemasses** [Ofthemasses/VimVentures#10]
Currently the game does not have a start menu. Thanks to previous work I should be able to make use of the IState interface to handle this.

Though, I want to be able to enter the game and exit to the menu. To do this I will need to improve the handling of the terminal, there are cases where X11 cannot find the terminal and the game crashes. Also, I do not want to have to recreate a terminal on game start if it is not necessary.

This issue may drive me to improve input handling, though IState can handle this with the IState::SendEvent method.

Finally, it will be worth making some classes for handling UI and text rendering. SDL2 comes with TTF rendering but I will need to investigate how this will interact with my OpenGL context.

## To-Do
- [x] Create a state for the start menu
- [x] Handle switching between the start menu state and MissionState. This may involve handling X11 crashes
- [x] Ensure MissionState (VimEmulator) only creates a terminal when needed. Also should reset the terminal if a need terminal instance is not required
- [x] Create Title text ~~, will involve creation of a Text handling class~~
- [x] Create UI for "Start" and "Quit". Should be traversable via the 'j' (up) and 'k' (down) keys
- [x] ON MERGE MARK AND RELEASE AS VERSION 0.0.2
