### ISSUE TITLE
Intro Sequence

### ISSUE THREAD

**Issue by Ofthemasses** [Ofthemasses/VimVentures#12]
## Description
We need an intro sequence to introduce the player to the world of the game.

The player will start stranded on a asteroid and need to fix their ship to *start* the game. This is our tutorial.

To introduce this world we will play an animated slideshow, maybe some sounds/music with text.

This sequence will only use test stills, a new issue will be created later addressing actual assets for this portion of the game.

## To-Do
- [x] Three Intro Pictures
- [x] Basic storyboard
- [x] New State for Intro
- [x] Play Intro (Sliding Images)
- [x] Implement a skip feature
