### ISSUE TITLE
Create Asteroid Shooter Mini-Game

### ISSUE THREAD

**Issue by Ofthemasses** [Ofthemasses/VimVentures#18]
## Description
As part of the basic tutorial we will cover the use of `$` (end of line). 

To do this we will get the player to move their cursor up and down and press `$` to jump to the end of lines and destroy the asteroids and then `0` to go back. Here a little example:

```
1 ▉               *
2              
3                         *
4       *
5 X (Game over line 5)
```

## To-Do
- [x] Create Game State
- [x] *Render* the game to a document
- [x] Stream the document to the vim instance window
- [x] Keep track of deleted 'asteroids' *(\*)*
