### ISSUE TITLE
Project Wiki

### ISSUE THREAD

**Issue by Ofthemasses** [Ofthemasses/VimVentures#2]
## Description
Create the project wiki. This should contain generated code docs, the philosophy for the project, and a copy of my VimWiki I use for planning and ideas.

## To-Do
- [x] Decide hosting, options: GitHub wiki, GitHub pages, personal website. &larr; Personal Website
- [x] Find the best option for generating code docs. &larr; Doxygen
- [x] Write an introduction section. 
- [x] Write a project philosophy section, this will include more details about the choice of licensing.
- [x] Setup sections for docs and planning.
- ~~Create a GitHub action that updates the code docs automatically.~~ <- This will be updated via the server
- ~~Set up a script to update the wiki with my VimWiki server once a day, so the planning and thought process of this project is open to the public.~~ <- Current provider does not allow for this (syncthing)
- [x] Link the project wiki in the README
